// contract test (QA report spec §4): shared/report-templates/fixtures/remarks-1.json is the
// fixture both android and web assert buildRemarks/printedRemarks against -- generated by the
// other agent's shared/report-templates/fixtures/reference.py (build_remarks). Reads the file
// directly off disk via a relative path, same trick ReportProgressFixtureTest.kt uses: gradle
// runs unit tests with :app (android/app) as the working directory, so "../../shared/..." lands
// on the repo-root shared/ folder both platforms read from -- no copy of the fixture lives in
// this module.
package bd.sicip.qavisit.domain.report

import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import org.junit.Assert.assertEquals
import org.junit.Test
import java.io.File

@Serializable
private data class RemarksCase(
    val case: String,
    val item: CriteriaItem,
    val entry: JsonObject,
    val bullets: List<String>,
    val printed: List<String>,
)

private val fixtureJson = Json { ignoreUnknownKeys = true }

private fun loadCases(): List<RemarksCase> {
    val text = File("../../shared/report-templates/fixtures/remarks-1.json").readText()
    return fixtureJson.decodeFromString<List<RemarksCase>>(text)
}

class RemarksFixtureTest {
    @Test
    fun `remarks-1 fixture matches buildRemarks and printedRemarks exactly`() {
        val cases = loadCases()
        assertEquals("fixture should be non-empty", true, cases.isNotEmpty())
        cases.forEach { case ->
            // entry is the fixture's raw {opts,evidence,note,ai} object -- wrapped as
            // ReportData(root) the same shape a report's own data.criteria[itemId] entry has,
            // just addressed directly instead of via a report's full {fields,checks,cards,...}.
            val data = ReportData(
                buildJsonObject {
                    put("criteria", buildJsonObject { put(case.item.id, case.entry) })
                },
            )
            assertEquals("[${case.case}] bullets", case.bullets, buildRemarks(case.item, data))
            assertEquals("[${case.case}] printed", case.printed, printedRemarks(case.item, data))
        }
    }
}
